###exclude public privilege for pci#########
--------------------------------------------
--SYS
grant EXECUTE on DBMS_ADVISOR to SYS;
grant EXECUTE on DBMS_JAVA to SYS;
grant EXECUTE on DBMS_JAVA_TEST to SYS;
grant EXECUTE on DBMS_LDAP to SYS;
grant EXECUTE on DBMS_LOB to SYS;
grant EXECUTE on DBMS_OBFUSCATION_TOOLKIT to SYS;
grant EXECUTE on DBMS_SCHEDULER to SYS;
grant EXECUTE on DBMS_SQL to SYS;
grant EXECUTE on DBMS_XMLGEN to SYS;
grant EXECUTE on DBMS_XMLQUERY to SYS;
grant EXECUTE on HTTPURITYPE to SYS;
grant EXECUTE on UTL_FILE to SYS;
grant EXECUTE on UTL_HTTP to SYS;
grant EXECUTE on UTL_INADDR to SYS;
grant EXECUTE on UTL_SMTP to SYS;
grant EXECUTE on UTL_TCP to SYS;
grant EXECUTE on DBMS_JOB to SYS;
grant EXECUTE on DBMS_RANDOM to SYS;

--APEX_030200
grant EXECUTE on DBMS_ADVISOR to APEX_030200;
grant EXECUTE on DBMS_JAVA to APEX_030200;
grant EXECUTE on DBMS_JAVA_TEST to APEX_030200;
grant EXECUTE on DBMS_LDAP to APEX_030200;
grant EXECUTE on DBMS_LOB to APEX_030200;
grant EXECUTE on DBMS_OBFUSCATION_TOOLKIT to APEX_030200;
grant EXECUTE on DBMS_SCHEDULER to APEX_030200;
grant EXECUTE on DBMS_SQL to APEX_030200;
grant EXECUTE on DBMS_XMLGEN to APEX_030200;
grant EXECUTE on DBMS_XMLQUERY to APEX_030200;
grant EXECUTE on HTTPURITYPE to APEX_030200;
grant EXECUTE on UTL_FILE to APEX_030200;
grant EXECUTE on UTL_HTTP to APEX_030200;
grant EXECUTE on UTL_INADDR to APEX_030200;
grant EXECUTE on UTL_SMTP to APEX_030200;
grant EXECUTE on UTL_TCP to APEX_030200;

--CTXSYS
grant EXECUTE on DBMS_SQL to CTXSYS;
grant EXECUTE on DBMS_XMLGEN to CTXSYS;
grant EXECUTE on DBMS_SCHEDULER to CTXSYS;
grant EXECUTE on DBMS_LOB to CTXSYS;

--DBSNMP
grant EXECUTE on DBMS_OBFUSCATION_TOOLKIT to DBSNMP;
grant EXECUTE on DBMS_JOB to DBSNMP;
grant EXECUTE on DBMS_RANDOM to DBSNMP;

--EXFSYS
grant EXECUTE on DBMS_ADVISOR to EXFSYS;
grant EXECUTE on DBMS_JAVA to EXFSYS;
grant EXECUTE on DBMS_JAVA_TEST to EXFSYS;
grant EXECUTE on DBMS_LDAP to EXFSYS;
grant EXECUTE on DBMS_LOB to EXFSYS;
grant EXECUTE on DBMS_OBFUSCATION_TOOLKIT to EXFSYS;
grant EXECUTE on DBMS_SCHEDULER to EXFSYS;
grant EXECUTE on DBMS_SQL to EXFSYS;
grant EXECUTE on DBMS_XMLGEN to EXFSYS;
grant EXECUTE on DBMS_XMLQUERY to EXFSYS;
grant EXECUTE on HTTPURITYPE to EXFSYS;
grant EXECUTE on UTL_FILE to EXFSYS;
grant EXECUTE on UTL_HTTP to EXFSYS;
grant EXECUTE on UTL_INADDR to EXFSYS;
grant EXECUTE on UTL_SMTP to EXFSYS;
grant EXECUTE on UTL_TCP to EXFSYS;
grant EXECUTE on DBMS_LOCK to EXFSYS;

--MDSYS
grant EXECUTE on UTL_FILE to MDSYS;
grant EXECUTE on DBMS_SQL to MDSYS;
grant EXECUTE on DBMS_LOB to MDSYS;
grant EXECUTE on DBMS_JOB to MDSYS;
grant EXECUTE on DBMS_RANDOM to MDSYS;
grant EXECUTE on UTL_HTTP to MDSYS;
grant EXECUTE on DBMS_XMLGEN to MDSYS;
grant EXECUTE on DBMS_JAVA to MDSYS;

--ORACLE_OCM
grant select on dba_scheduler_jobs to ORACLE_OCM;
grant select on v_$instance to ORACLE_OCM;
grant select on v_$parameter to ORACLE_OCM;
grant select on gv_$instance to ORACLE_OCM;
grant select on DBA_DB_LINKS to ORACLE_OCM;
grant select on dba_audit_trail to ORACLE_OCM;
grant select on v_$process to ORACLE_OCM;
grant select on dba_tables to ORACLE_OCM;
grant select on v_$session to ORACLE_OCM;
grant select on sys.v$database to ORACLE_OCM;

--OLAPSYS
grant EXECUTE on UTL_FILE to OLAPSYS;
grant EXECUTE on DBMS_SQL to OLAPSYS;
grant EXECUTE on DBMS_LOB to OLAPSYS;
grant EXECUTE on DBMS_SCHEDULER to OLAPSYS;

--SYSMAN
grant EXECUTE on DBMS_SQL to SYSMAN;
grant EXECUTE on DBMS_OBFUSCATION_TOOLKIT to SYSMAN;

--SYSTEM
grant EXECUTE on DBMS_SQL to SYSTEM;

--WMSYS
grant EXECUTE on DBMS_SQL to WMSYS;

--XDB
grant EXECUTE on UTL_FILE to XDB;
grant EXECUTE on DBMS_LOB to XDB;
grant EXECUTE on DBMS_SQL to XDB;
grant EXECUTE on DBMS_JOB to XDB;

--DMSYS
grant EXECUTE on DBMS_ADVISOR to DMSYS;
grant EXECUTE on DBMS_JAVA to DMSYS;
grant EXECUTE on DBMS_JAVA_TEST to DMSYS;
grant EXECUTE on DBMS_LDAP to DMSYS;
grant EXECUTE on DBMS_LOB to DMSYS;
grant EXECUTE on DBMS_OBFUSCATION_TOOLKIT to DMSYS;
grant EXECUTE on DBMS_SCHEDULER to DMSYS;
grant EXECUTE on DBMS_SQL to DMSYS;
grant EXECUTE on DBMS_XMLGEN to DMSYS;
grant EXECUTE on DBMS_XMLQUERY to DMSYS;
grant EXECUTE on HTTPURITYPE to DMSYS;
grant EXECUTE on UTL_FILE to DMSYS;
grant EXECUTE on UTL_HTTP to DMSYS;
grant EXECUTE on UTL_INADDR to DMSYS;
grant EXECUTE on UTL_SMTP to DMSYS;
grant EXECUTE on UTL_TCP to DMSYS;
grant EXECUTE on DBMS_LOCK to DMSYS;
grant EXECUTE on DBMS_JOB to DMSYS;
grant EXECUTE on DBMS_RANDOM to DMSYS;



@?/rdbms/admin/utlrp.sql



select 'Revoke '||PRIVILEGE||' on '||TABLE_NAME|| ' from public;'
FROM DBA_TAB_PRIVS
WHERE GRANTEE='PUBLIC'
AND PRIVILEGE='EXECUTE'
and owner='SYS'
and TABLE_NAME in ('DBMS_ADVISOR','DBMS_CRYPTO','DBMS_JAVA','DBMS_JAVA_TEST','DBMS_LDAP','DBMS_LOB',
'DBMS_OBFUSCATION_TOOLKIT','DBMS_BACKUP_RESTORE','DBMS_SCHEDULER','DBMS_SQL','DBMS_XMLGEN','DBMS_XMLQUERY',
'UTL_FILE','UTL_INADDR','UTL_TCP','UTL_MAIL','UTL_DBWS','UTL_SMTP','UTL_HTTP','UTL_ORAMTS','HTTPURITYPE');