select JOB_NAME,STATUS,LOG_DATE,ADDITIONAL_INFO
from ALL_SCHEDULER_JOB_LOG 
where OWNER in ('TEMP','DISCWEB')
order by LOG_DATE,job_name;

SELECT JOB_NAME, max_runs,STATE,ENABLED,START_DATE,NEXT_RUN_DATE,LAST_RUN_DURATION
FROM ALL_SCHEDULER_JOBS 
where owner in ('TEMP','DISCWEB') 
order by start_date;

SELECT  OWNER,PROGRAM_NAME,PROGRAM_TYPE,ENABLED,SUBSTR(PROGRAM_ACTION,1,70) 
FROM ALL_SCHEDULER_PROGRAMS 
where owner in ('TEMP','DISCWEB') ;