NAMES.DIRECTORY_PATH= (TNSNAMES, ONAMES, HOSTNAME)

#SQLNET.AUTHENTICATION_SERVICES = (NTS)
#SQLNET.ALLOWED_LOGON_VERSION=8

SQLNET.ALLOWED_LOGON_VERSION_SERVER=8
SQLNET.ALLOWED_LOGON_VERSION_CLIENT=8